bosun-ai/kwaak

Dockerfile

This pull request updates the Dockerfile to include the installation of `make`, ensuring that the build environment has all necessary tools available. This change is added to the section where system packages are installed using `apt-get`. This should not disrupt the build process.
---
<details>
<summary>Message History</summary>
<details>
<summary>ℹ System</summary>
```markdown
You are an autonomous ai agent tasked with helping a user with a code project. You can solve coding problems yourself and should try to always work towards a full solution. The project is called kwaak and is written in Rust
- Try to …
```

Add `make` installation to Dockerfile

---

src/agent/docker_tool_executor.rs
src/git/github.rs

- **fix: Truncate tool output for pull requests**
- **Clippy**

fix: Truncate tool output for PRs

---

Cargo.lock
Cargo.toml
src/agent/mod.rs
src/agent/tools.rs
src/agent/v1.rs
src/cli.rs
src/git/github.rs
src/main.rs
templates/github_search_results.md

- **Add github code search tool**
- **More concise formatting and handle no results**
- **Add `fetch_url` tool**

feat(tools): Agents can now search code on github and fetch urls (like from github)

---

Cargo.lock
Cargo.toml
src/agent/tools.rs
src/agent/v1.rs
templates/tavily_search_results.md

This pull request updates the "tavily" crate to version 2.0.3 in the kwaak project. The update has been tested successfully, with all existing tests passing. However, the current test coverage is 17.56%, indicating potential for additional test improvements in the future. This update ensures compatibility with the latest features of the tavily crate.
---

Update tavily crate to version 2.0.3

---

src/agent/tools.rs
templates/pull_request.md

This update modifies the `tools.rs` file to include guidelines for using conventional commits in pull request titles. This ensures structured commit messages and enhances the readability of commit history.
- Updated the `CreateOrUpdatePullRequest` tool description with conventional commit guidelines like `feat:`, `fix:`, `docs:`.
These changes help ensure consistency and clarity in pull request titles.
---

feat: Add conventional commits guidelines to pull request tool description

---

Cargo.lock
Cargo.toml
src/main.rs
src/onboarding.rs
tests/cli_init.rs
tests/snapshots/cli_init__creates_a_new_init_file.snap.new

Ran out of disk space, so it didn't add any tests and failed to create the pr :>
Guess I'll just have to do it myself.
#48

fix: Run init before loading config

---

src/agent/v1.rs
src/frontend/chat_mode/ui.rs

- **Use pretty icons**
- **Shorter title**
- **Enable wrap again**

feat: Show message status with nice icons

---

src/chat_message.rs
src/commands.rs
src/frontend/app.rs
src/frontend/chat_mode/on_key.rs
src/frontend/chat_mode/ui.rs
src/frontend/mod.rs
src/frontend/tests/chat_mode.rs
src/frontend/ui_event.rs
src/frontend/ui_input_command.rs

- **Clean up delete chat and events**
- **Add unit tests for all chat* methods**

fix: Delete chat should not panic on index out of bounds

---

Cargo.toml
src/agent/mod.rs
src/agent/tools.rs
src/chat.rs
src/chat_message.rs
src/commands.rs
src/config/api_key.rs
src/config/config.rs
src/config/defaults.rs
src/frontend/ui_input_command.rs
src/indexing/mod.rs
src/indexing/query.rs
src/kwaak_tracing.rs
src/lib.rs
src/main.rs
src/repository.rs
src/runtime_settings.rs
src/storage.rs
src/test_utils.rs
src/util.rs
tests/test_tools.rs

- **refactor: Rework kwaak into a lib for easier integration testing**
- **fix: Include hidden and ignore case for file search and code search**

fix: Ignore hidden and case with file and code search

---

src/agent/conversation_summarizer.rs
src/agent/v1.rs

Heuristically seems to work very well, aiming for next release

Add the current diff to the summarizer

---

README.md

Arguments failed to parse on the tool call when creating the PR. This a bug that needs to be fixed.
Part of #48

docs: Update readme with all configuration settings

---

README.md

The ToC in the readme was outdated. Fixes #154

docs(README): Update TOC in readme

---

Cargo.toml
src/commands/handler.rs
src/config/api_key.rs
src/config/config.rs
src/config/llm_configuration.rs
src/frontend/app.rs
src/lib.rs
tests/cli_init.rs
tests/test_tools.rs

- **Remove testing feature flag**
- **Improve tests/ consistency and add tests for api key**

fix: Improve test consistency and remove testing feature flag

---

kwaak.toml
src/agent/v1.rs
src/config/config.rs
src/config/llm_configuration.rs
src/git/github.rs
src/main.rs
src/test_utils.rs
templates/kwaak.toml

BREAKING CHANGE: Configuration now has all api keys in the root. This simplifies configuration and allows us to give better errors if something is off. You can still overwrite openai api keys per task if needed.

feat(config)!: Simplify configuration for better user errors

---

.github/workflows/coverage.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
kwaak.toml
src/config/api_key.rs
src/config/defaults.rs

- **First try simple test**
- **Update deps**

fix(ci): Fix pipelines

---

README.md

Updated README with a more engaging tagline.
---

docs: Update README tagline

---

Cargo.lock
Cargo.toml
src/cli.rs
src/config/llm_configuration.rs
src/main.rs
src/onboarding.rs
src/test_utils.rs
taplo.toml
templates/kwaak.toml
tests/cli_init.rs

- **Applied diff**
- **wip**
- **Interactive onboarding**
- **Clippy fix**
- **Update test**
- **Nice copy**
- **Add link**

feat: Guided onboarding

---

README.md
src/agent/v1.rs
src/config/config.rs
src/config/defaults.rs
src/main.rs
src/onboarding.rs
templates/kwaak.toml

- **feat: Opt out of auto pushing to remote**
- **feat: Opt-out pull request tool**
- **feat: Add commands to onboarding**
- **fix: Remove base_url from onboarding**

feat: Opt-out of auto pushing to remote and pull requests

---

.gitignore
Cargo.lock
Cargo.toml
README.md
src/agent/conversation_summarizer.rs
src/agent/tool_summarizer.rs
src/agent/v1.rs
src/config/api_key.rs
src/config/config.rs
src/config/llm_configuration.rs
src/onboarding.rs
templates/kwaak.toml

~~Still need to add i.e. fastembed so there is an embedding alternative that doesn't require anything external~~

feat: Support many LLMs via OpenRouter

---

src/main.rs
src/onboarding/commands.rs
src/onboarding/git.rs
src/onboarding/llm.rs
src/onboarding/mod.rs
src/onboarding/project.rs
src/onboarding/util.rs
tests/cli_init.rs

Makes some small improvements to the onboarding flow
- **Remove owner/repo name detection and make auto push to remote false by default**
- **Add a header for the llm part**
- **Remove all panics when onboarding**

feat: Onboarding flow improvements

---

.github/workflows/release.yml
Cargo.lock
Dockerfile
dist-workspace.toml

fix: Add libstc and build-essential to apt build requirements

fix(ci): Use more stable GA runner and add libstcpp6

---

README.md
src/config/config.rs
src/frontend/app.rs
src/main.rs

- **fix(config): Use double separators in env config overrides**
- **feat: Optionally hide the top header in the ui**

feat: Optionally hide top header in UI

---

src/agent/v1.rs
src/indexing/garbage_collection.rs
src/runtime_settings.rs

Ensure the last cleaned up date is properly set in all cases. Also only consider files that match the indexed extensions.
- **fix: Also set last cleaned up date when no changes were found**
- **fix: Skip files if they do not match indexed extensions**

fix: Garbage collection improvements and fixes

---

benchmarks/swe/src/kwaak_bench_swe/main.py

This script lets us easily clean up and retry SWE-bench runs.

feat(benchmarks): Command to remove failed/unsuccesful SWE-bench results

---

src/agent/commit_and_push.rs
src/agent/mod.rs
src/agent/v1.rs
src/test_utils.rs

Refactors the auto commit and push to a separate struct and use an llm to generate pretty commit messages
Resolves #184

feat: Generate commit messages with llm

---

src/agent/conversation_summarizer.rs

- **fix(anthropic): Remove tool uses when summarizing context; fixes breaking issue**
- **Bit of prompt tuning**

fix(anthropic): Remove tool uses when summarizing context; fixes breaking issue

---

Cargo.lock
Cargo.toml
src/kwaak_tracing.rs
src/main.rs

- **chore(deps): bump the minor group across 1 directory with 12 updates**
- **Fixes for otel upgrade and remove nonfunctional cfgs**

chore(deps): Update otel and other deps

---

src/agent/commit_and_push.rs
src/config/config.rs

Specifically for benchmarking as it just increases the cost without
value. Others might find it useful as well.

feat: Opt-out commit message generation

---

Cargo.lock
Cargo.toml
src/agent/commit_and_push.rs
src/config/llm_configuration.rs
src/test_utils.rs
tests/snapshots/diff_commands__diff.snap
tests/snapshots/retry_chat__after_retry.snap
tests/snapshots/retry_chat__before_retry.snap

Tested with claude sonnet and openai 4o and 4o mini with the diff of this PR. Looks good now.

fix: Prompt so that commit messages are (way more) consistent

---

src/agent/conversation_summarizer.rs

improving the summarizer prompt
Also removed the "Previously you did" section which seemed to be a duplicate of the "Since then you did" section

feat(agent): Better task focus with improved summarizer

---

Dockerfile

Fixes https://github.com/bosun-ai/kwaak/issues/367

build: optimize docker build time

---

src/cli.rs
src/config/config.rs
src/evaluations/patch.rs
src/main.rs

feat: Support storing `kwaak.toml` in `.config/kwaak.toml`

---

README.md
src/onboarding/mod.rs

- **Add a warning for ollama models**
- **Remove rg/fd from onboarding**

chore: Remove rg/fg from onboarding and add warning for Ollama

---

kwaak.toml
src/agent/session.rs
src/lib.rs
src/main.rs

fix: Useful error instead of panic when dockerfile not found

---

src/agent/agents/coding.rs
src/agent/agents/delegate.rs
src/agent/mod.rs
src/agent/util.rs
src/commands/handler.rs
src/commands/responder.rs
src/evaluations/logging_responder.rs
src/evaluations/tests/mod.rs
src/evaluations/tool_evaluation_agent.rs
src/frontend/actions/diff.rs
src/frontend/app_command_responder.rs
src/indexing/mod.rs
src/indexing/progress_updater.rs
src/indexing/repository.rs

Required for using in both the gui and a server

refactor: Responder is now async and responses do the serde

---

src/agent/conversation_summarizer.rs
src/agent/git_agent_environment.rs
src/agent/tools/mod.rs
src/agent/tools/patch_file.rs
src/chat.rs
src/frontend/actions/github.rs
src/frontend/app.rs
src/frontend/chat_mode/chat_list_widget.rs
src/frontend/chat_mode/on_key.rs
src/kwaak_tracing.rs

Output becomes like this:
```
bow/public/demo/images/landing/mockup-desktop.svg
21:<image id="image0_1432_2516" width="2011" height="1183" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9sAAASfCAYAAACtPp2qAAAgAElEQVR4Aey9a6wt6Xnn9dZlrbXPOd1u22NnEl8ydiaZXCAXx44nTjIjKyGABzIJjFohkxgFkIxGMGgQRuIDMHxAAr4gJFA+IEDiAx9QECNBhqCRBs1MEmUy0khEQSaJiXHGyZDY7XZ3n8ve61aFfs+/nlW119n7nH1O9z7us+tf3ftU1Xt53uf5vc97qXpXVVXFmwmYwHND4KMf/ejtrrt9p22rk3 [... 6 more matches]
22:<image id="image1_1432_2516" width="3074" height="2220" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAADAIAAAisCAYAAABoVaEaAAAMamlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAhGQEnoTpFcpIbQAAlIFGyEJJJQYE4KKvSwquHYRwYquiii6ugJiQ+xlUex9saCirKIuiqLyJgV03Ve+d75v7vz558x/zpw7N/cOANq9XIkkH9UBoEBcKE2MDGWOTs9gkjoABWgDOtAHZlyeTMJKSI …
```

fix: Add maximum amount of columns to the output of ripgrep
