src/agent/docker_tool_executor.rs

PR created by kwaak, but PR body too big
Feedback: Seems it didn't run rustfmt

fix: Container can be both exiting and removing in tests

---

src/agent/tools.rs

If the file does not exist, inform the llm instead of returning an error.

fix: Accept non zero exit when reading files

---

src/chat.rs
src/cli.rs
src/frontend/app.rs
src/frontend/chat_mode/on_key.rs
src/frontend/chat_mode/ui.rs
src/main.rs

This pull request implements a new keybinding (`Ctrl+E`) to scroll the chat view to the last message while keeping 50% of it visible. The following changes were made:
- Added a keybinding in `on_key.rs` to handle the `Ctrl+E` command.
- Modified the `render_chat_messages` function in `ui.rs` for correct scroll positioning to ensure the last message is half-visible on the screen.
- Verified with existing tests to ensure no regressions occurred.
This feature enhancement improves user interaction by providing a quick way to access the most recent message without losing context in the chat view. The changes have been tested and verified, although the specific feature lacks dedicated test coverage and may require additional tests in the future to improve coverage metrics. Please review the …

Implement Scroll-to-End Keybinding

---

README.md
src/cli.rs
src/main.rs

- Refactored the `kwaak` CLI to leverage `clap` subcommands rather than relying on the `--mode` argument.
- Ensured that each mode now operates under its specific subcommand, with the TUI being the default subcommand.
- Updated `src/cli.rs` to define new subcommands and their respective arguments.
- Modified `src/main.rs` to accommodate the subcommand structure and invoke the correct functionality based on user input.
- All existing tests have been run successfully, indicating that the refactored CLI commands operate correctly and that no regressions have been introduced.
- Checked test coverage to ensure that the new subcommand structure was properly validated by the existing tests.
This refactor enhances code readability and maintainability by aligning with best practices for CLI …

feat: Refactor CLI to Use Subcommands Instead of --mode

---

src/config/config.rs
src/kwaak_tracing.rs

- Updated the `Config` struct in `src/config/config.rs` to include a new field `otel_enabled`.
- Modified logic in `src/kwaak_tracing.rs` to enable OpenTelemetry tracing based on both a feature flag and the `otel_enabled` configuration setting.
- Changed the default value of `otel_enabled` to `false`.
- Updated deserialization tests in `src/config/config.rs` to reflect this change.
- Ensured all tests pass successfully after the modifications.
---

feat: Make `otel` Feature Contingent on Feature Flag and Configuration

---

src/commands.rs
src/frontend/app.rs
src/frontend/chat_mode/on_key.rs
src/frontend/chat_mode/ui.rs
src/frontend/ui_command.rs
src/frontend/ui_event.rs

This pull request introduces the `/delete_chat` command to the kwaak project, enabling users to delete specific chats within the application. Key changes include:
- Updated the `Command` enum in `src/commands.rs` to include the `DeleteChat` variant.
- Added support for parsing the `/delete_chat` command in `src/frontend/ui_command.rs`.
- Implemented handling for `UIEvent::ChatDeleted` in `src/frontend/app.rs`.
- All tests passed successfully with no regressions.
Further improvements and tests are recommended for areas with low coverage.
---

feat: Add /delete_chat command

---

src/indexing/garbage_collection.rs

- Modified the identification of removed files to limit it to those that have been removed only since the last indexed commit.
- Updated the `files_changed_since_last_index` method to utilize git to check for deleted files since a specific commit.
- Updated corresponding tests ensuring functionality handles recent deletions correctly.
---

feat: Enhance Garbage Collection to Handle Removed Files Since Last Index

---

Cargo.lock
Cargo.toml
src/agent/v1.rs
src/commands.rs

Ensure the `rename_chat` function truncates chat titles to a maximum of 30 characters. This adjustment helps avoid any potential issues with chat title length in the application.
---

fix: truncate chat titles to 30 characters in rename_chat function

---

Cargo.lock
Cargo.toml
src/agent/v1.rs
src/chat.rs
src/chat_message.rs
src/commands/command.rs
src/commands/handler.rs
src/commands/mod.rs
src/commands/responder.rs
src/commands/running_agent.rs
src/frontend/app.rs
src/frontend/app_command_responder.rs
src/frontend/chat_mode/message_formatting.rs
src/frontend/chat_mode/on_key.rs
src/frontend/mod.rs
src/frontend/ui_event.rs
src/frontend/ui_input_command.rs
src/indexing/repository.rs
src/main.rs

Reworks command handling such that it always takes a dynamic responder. This PR is a big enabler, making a lot of features on the roadmap easier to implement.
This allows full decoupling with command handling from the responder, making it easier to implement features like getting the diff from a running agent.
For the latter, this PR contains a few changes in prep for that as well.

refactor: Rework command handling

---

Cargo.lock
Cargo.toml
src/kwaak_tracing.rs
src/main.rs

Many hosted parties (openobserve, grafana, etc) do not support pure grpc

fix(tracing): Run otel in http mode if enabled

---

src/frontend/chat_mode/on_key.rs
src/kwaak_tracing.rs
src/main.rs

Implemented additional keyboard shortcuts `ctrl+enter` and `shift+enter` for sending messages to the agent, alongside the existing `ctrl+s` functionality. This change enhances user convenience by allowing multiple key combinations to trigger the same action.
---

feat: Add ctrl+enter and shift+enter as shortcuts to send a message

---

src/frontend/chat_mode/on_key.rs

The modification alters how the arrow keys are handled within the chat mode of the application. We want the arrow keys to scroll the chat history only when the input box is empty. When there is content in the chat input, the arrow key presses are directed to text navigation operations within the input box. 
- In `src/frontend/chat_mode/on_key.rs`, enhanced the checks under the `match` expression.
- Ensure up and down keys handle scrolling for empty input.
- Route key presses for navigation to text input when there's content in the `current_input`.
- All tests passed successfully post-modification.
---

feat: Adjust arrow key behavior in chat input

---

src/agent/mod.rs
src/agent/util.rs
src/agent/v1.rs
src/config/config.rs

We want to be able to experiment with different kinds of agents, without affecting our main users. With this an agent model can be selected in the config (defaulting to what we think works best). Later, we could i.e. add a development agent, experiment with multi-agent setups, etc, without affecting our users.

refactor: Add support for experimenting with multiple agents

---

.github/workflows/tests.yml
kwaak.toml
src/agent/v1.rs
tests/test_tools.rs

The line edits introduced last week show inconsistent behaviour. For now, move back to whole edit mode. We can revisit different edit modes later.

fix: Disable line edits for now

---

Cargo.lock
Cargo.toml
README.md
kwaak.toml
src/agent/conversation_summarizer.rs
src/agent/mod.rs
src/agent/tool_summarizer.rs
src/agent/tools.rs
src/agent/util.rs
src/agent/v1.rs
src/config/config.rs
src/frontend/chat_mode/message_formatting.rs
src/git/util.rs
src/test_utils.rs
tests/test_tools.rs

This PR improves line editing, and makes it opt-in. Different kinds of edits work best for different kind of llms (and optimizations here are probably void in a couple of weeks anyway).
- Format line numbers as `1|<line>`. Python needs white space correctly indented.
- Disable regular file reading. With line numbers ONLY.
- Nudge LLM to use write file for new files.
- Append instead of prepend, more intuitive and enables appending to end of file as well.
- Renamed replace block to edit file
- More elaborate prompt on how the edit file works

feat: Reworked, opt-in line editing

---

src/cli.rs
src/main.rs
tests/cli_init.rs

This pull request includes changes to ensure that Kwaak does not start the TUI or run the agent if the current directory contains uncommitted changes ("dirty" state), unless overridden with the `--allow-dirty` flag.
- Added `--allow-dirty` flag for command-line parsing in `src/cli.rs`.
- Implemented logic in `src/main.rs` to check for a dirty git directory and prevent command execution unless `--allow-dirty` is specified.
- Adjusted test cases in `tests/cli_init.rs` to commit changes or incorporate the `--allow-dirty` flag where appropriate.
- All existing and new tests are passing.
Fixes #167 
---

feat: add dirty repository check with --allow-dirty flag

---

Cargo.lock
Cargo.toml
Dockerfile
Dockerfile.tests
README.md
kwaak.toml

Uses the new executor. Instead of relying on direct shell execution, it uses grpc. The client is copied in with 2 other deps (rg/fd) when building the image. It makes the whole experience a lot smoother.
Additionally, a host of errors and inconsistencies were fixed.
Fixes #251 and #250

feat: Simplify docker with new executor

---

Cargo.lock
Cargo.toml
README.md
src/agent/v1.rs
src/config/config.rs
src/config/llm_configuration.rs
src/evaluations/tool_evaluation_agent.rs
src/indexing/query.rs
src/indexing/repository.rs

Added backoff functionality for open-ai/open-router llm calls. Also did some minor refactoring to allow for this feature. 
doesn't close, but related to https://github.com/bosun-ai/kwaak/issues/296

feat: Improve rate and context limit handling for OpenAI and OpenRouter with configurable backoff

---

src/agent/conversation_summarizer.rs

fix: Do not include system prompt when summarizing and skip summary if agent stopped

---

kwaak.toml
src/agent/agents/coding.rs
src/agent/agents/delegate.rs
src/agent/conversation_summarizer.rs
src/indexing/query.rs

Improvements here follow from experimenting with sonnet 3.7. Improves the CoT prompt by being more explicit on what it should include. Additionally tunes the summarization step to include more information (and what information). So far, the results are promising, especially with 3.7. Seems like a large leap forward.
Additionally reduced the initial context a bit. Still very much a heuristic, but it improves the initial boot performance significantly. We only want to ground the agent anyway, not provide the full solution.

feat: Significant improvements to Chain-of-Thought prompts 

---

src/indexing/garbage_collection.rs
src/indexing/query.rs
src/indexing/repository.rs
src/runtime_settings.rs
src/storage.rs

commit 4c7c6cfc5ce58443fd3627be092af802c6e9ca64
refactor: simplify db init code
commit 8d4146614c4f5c422302a62ec18f31b45c16f2a7
chore: remove unnecessary Arc wrappers around DB
A fairly common pattern in types which implement clients (db, web, etc.)
is to have an inner type which is Arc wrapped. Both LanceDB and Redb are
such types. This commit replaces the unnecessary Arc wrappers around
these types in the storage module and all the places where they are used
with a simple owned type which is cloned when needed.
---
Note: this is something I noticed when taking a bit of a quick read through the code base. I haven't been able to get kwaak working due to https://github.com/bosun-ai/kwaak/issues/338, so unsure if this is working correctly. Slapping the PR up regardless. Also, I do note that …

refactor: Simplify db code

---

src/frontend/chat_mode/message_formatting.rs

On my color theme these make the text incredibly difficult to read.
Dim on its own works pretty well in many sitations.
---
The style I personally use is Aardvaark blue. I created this specifically for TUI usage after not finding a theme which met all the following criteria:
1. colors matched their name (i.e. yellow is not orange)
2. colors have enough contrast to work against the all of the following: default background, black, white, dark grey, grey
3. normal and bright versions of the colors are different
4. the default background was not black or white
5. shades of greys were properly ordered (i.e. black, dark grey, grey, white, bright white)
We use it for all the Ratatui screenshots.
See:
- https://github.com/ratatui/ratatui/blob/main/examples/README.md#color-explorer
- …

style: don't use dark grey and dim together

---

README.md

Now packaged in Arch Linux repos: <https://archlinux.org/packages/extra/x86_64/kwaak/> 🥳

docs: Add instructions for Arch Linux

---

src/lib.rs

Previously this was configured to have tracing play nice with lancedb. Doesn't seem to be necessary anymore.
I'm not sure if it's just a limit or also affects optimizations. Either way doesn't hurt to remove.

fix(build): Compile time recursion limit back to default

---

Cargo.lock
Cargo.toml
src/frontend/app.rs
src/lib.rs

When there is an update available:
When there is no update available:
Resolves #284

feat: Check for updates on boot with a more compact header

---

Cargo.lock
Cargo.toml
Dockerfile
kwaak.toml
src/main.rs

Allow testing tools fast in the projects executor (if they use it) for faster debug cycles.
Additionally this uses `cargo test --no-run` to build the docker caches, as for reasons unknown it rebuilds when going from build to test.
Updated crates while I was at it. Might as well keep that in.
---
**previous notes**
Beside all the docker shenanigens, there seem to be recent issues with running kwaak's own tests inside docker. This gives a fast feedback loop.
`kwaak test-tool <TOOL_NAME> [TOOL_ARGS]`
or
`cargo run -- test-tool <TOOL_NAME> [TOOL_ARGS]`
Additionally uses cargo test --no-run over cargo build. For reasons unknown cargo isn't reusing the cache from cargo build. Tried figuring it out with `CARGO_LOG=cargo::core::compiler::fingerprint=info cargo test`, but no luck. Also tried with …

fix: Quick test tools in the docker executor

---

src/commands/handler.rs
src/commands/responder.rs
src/evaluations/tests/mod.rs
src/frontend/actions/diff.rs
src/frontend/app_command_responder.rs
src/main.rs

The Uuid wasn't needed anymore with the new design. The app now expects the responder to know where it should go (duh).
Also implemented default members. So now, if you want to implement a custom responder, all you need is `send(&self, response: Command::Response)`.

refactor: Remove Uuid from command responses and implement default members

---

README.md
src/agent/session.rs
src/config/config.rs
src/config/mod.rs
src/config/tools.rs

After some thought I figured it would be nicer if users don't have to deal with the double negation. Additionally, there are also tools that are disabled by default. With this we can support both from the config level as well (even though we don't).
Bonus, we can (later) clean up session::available_tools and instead create the default list purely on the config. I feel that is where it belongs.
I think:
```toml
[tools]
write_file = false
run_tests = false
```
reads better than:
```toml
disabled_tools = ["write_file", "run_tests"]
```

feat: Rework tool configuration to support Opt-in as well

---

src/onboarding/llm.rs
src/onboarding/mod.rs
templates/kwaak.toml

Proper fix can come later. Perhaps in #351. I.e. generate the real config types, then tie it all together in the toml file. Could also then resume from an existing toml. Additionally, any comments could maybe be pulled from doc comments.

fix: Set Ollama embedding model correctly during onboarding

---

Dockerfile

Pfft curb my enthousiasm, bind mounts only work during build. So back to the original solution. It does now use ldd instead of ld in the image. That solves my memory issues.

chore: Use lld for faster local docker builds

---

Cargo.lock
Cargo.toml
README.md
src/indexing/garbage_collection.rs
src/indexing/query.rs
src/indexing/repository.rs
src/lib.rs
src/main.rs
src/runtime_settings.rs
src/storage.rs
src/test_utils.rs

Stats incoming. Replaces lancedb and redb with duckdb.
~200 less dependencies.
Requires a swiftide release.
***Before**
**After**
TODO:

feat!: Migrate to duckdb

---

Cargo.lock
Cargo.toml
src/indexing/garbage_collection.rs

Getting a 'cannot capture foreign exceptions' in the diff integration tests.

chore(deps): Update duckdb to 1.2.1

---

src/agent/snapshots/kwaak__agent__tool_summarizer__test__prompt_render_where_tool_output_has_jinja.snap
src/agent/tool_summarizer.rs
src/templates.rs
templates/tool_summarizer.md

In the Django SWE results, the summarizer failed because there is inline jinja.
Reworked the template so it's a bit nicer. I'm sure it can be nicer still.

fix: Tool summarizer should escape output

---

Cargo.lock
Cargo.toml
src/agent/mod.rs
src/agent/session.rs
src/agent/tools/mod.rs
src/commands/handler.rs
src/evaluations/patch.rs
src/evaluations/ragas.rs
src/indexing/mod.rs
src/indexing/query.rs
src/indexing/repository.rs
src/main.rs
src/test_utils.rs
tests/test_tools.rs

Lays the ground for dependency injecting the index into the application. Instead of gross boundary violations everywhere, the command handler is now started with an Index (DuckdbIndex here).
Exact interface and changes will likely still change, but this puts it nicely at the seams. There's still some spots where the index could be used but isn't.
It enables the following future changes (where as I see it, the hard part is now done):
- Running the kwaak backend with a different database
- Running the same kwaak backend with different pipelines
- Running kwaak on multiple repositories
- Running the index in a hosted environment
Requires bosun-ai/swiftide#720 as I wanted the pipelines to be generic over the search strategy but tools didn't support generics.

refactor: Index behind an interface

---

src/frontend/actions/mod.rs

Issue turned out to be simple. Since we now always rely on the agent to call `stop`, the last message might be empty. This fix makes sure it uses the last message with actual content.
Fixes #472

fix: filter out empty messages in copy_last_message function

---

src/chat.rs
src/commands/command.rs
src/commands/handler.rs
src/frontend/actions/github.rs
src/frontend/actions/mod.rs
src/frontend/actions/scroll.rs
src/frontend/app.rs
src/frontend/chat_mode/chat_messages_widget.rs
src/frontend/chat_mode/input_bar_widget.rs
src/frontend/chat_mode/message_formatting.rs
src/frontend/chat_mode/ui.rs
src/main.rs
src/test_utils.rs
tests/diff_commands.rs

Requires all commands needing it to include a repository in their command event. A repository is fully serializable (pure config), so this should be fine.
This makes it possible in the future to have different chat sessions with different repositories or run the command handler in a server.

refactor: Prepare for multi repository support

---

Cargo.lock
src/agent/agents/coding.rs
src/agent/agents/delegate.rs
src/agent/running_agent.rs
src/commands/handler.rs
src/evaluations/tool_evaluation_agent.rs

Allows retrieving the builder of an agent so that it can be modified if needed

refactor: Split agent building from creating a running agent for reuse
